[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# API routes - redirect to serverless functions
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback - handle all other routes by serving index.html
# This ensures React Router can handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
